{% set version = '0.6.1.2' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-d3heatmap
  version: {{ version|replace("-", "_") }}

source:
  fn: d3heatmap_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/d3heatmap_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/d3heatmap/d3heatmap_{{ version }}.tar.gz
  sha256: b3ce5dc60d5668a5a5ad087331d816a6682c92a89d6292788574fecf814491c5

build:
  noarch: generic
  number: 1006
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-base64enc
    - r-dendextend >=0.18.0
    - r-htmlwidgets
    - r-png
    - r-scales >=0.2.5
  run:
    - r-base
    - r-base64enc
    - r-dendextend >=0.18.0
    - r-htmlwidgets
    - r-png
    - r-scales >=0.2.5

test:
  commands:
    - $R -e "library('d3heatmap')"           # [not win]
    - "\"%R%\" -e \"library('d3heatmap')\""  # [win]

about:
  home: https://github.com/rstudio/d3heatmap
  license: GPL-3
  summary: Create interactive heat maps that are usable from the R console, in the 'RStudio'
    viewer pane, in 'R Markdown' documents, and in 'Shiny' apps. Hover the mouse pointer
    over a cell to show details, drag a rectangle to zoom, and click row/column labels
    to highlight.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
