appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: AKi2OrqxH2v/VR9dIeBfmfeGoxN3HLhIrqz/O3Bue+HQrZmD4iWEbI4RB60MZM+h8lu5HrJQI47seXb9TQ3GljcBA60UQWC6RwVIFrqAgb5ktJjZc2BPbwQkgscjNcTxh+zO9lsCjVd6bGcTvUl66VX16U6VRKw4KjrxReb+uMmDiwLl6z7QQPZjw9s7wLzVT+FuNvMoQEm/eyBoe1qcphtrktSRiHdPV7aWA1AuC4Tz3uYVEKhlk4mKo1TG7Gjqlm0V9ihMbE7flMP7SkVd7TY4JfFiY1uv4dOPKsl/DFXR6WkqavWw/mIJTZ4cqFCtt84QabyBO577grXsyiuXDdqYap5VYhNJl+BJEzg0i9Xg5OcKpMclb4WtDnD2LAOvZBgdF7mS9N95zCYrGPdKaxWwYmVed6oUZ8WKkWNh0tVDUat3alTXdefEQcIqgNEqvkBqKttz36Eg0kjC7RzUQcm6SrcKigjmO/wu+t4s/2OhFwkyNpuShuhQBoN2C4HZWOvjPkurjJCiqhsqKyHWgTG4ay8UFaU6bcPOYPph1rpLPXUywf+d8uTtg8IBR5sgGOUS7ZTQQAUcGuf5aZRWF+6OEtFG2lRcrGD3vvVUgfRHu2VM1QhLsajpJ3xqSBfsjjQy6k76eWZgRaCCqCzAoReuAVYz9WYhAaKoRg9wmec=
conda_forge_output_validation: true
